In [41]:
import numpy as np
num_states = 3
n_actions = 2
params = {"transition_record": np.zeros((num_states, num_states, num_states)), 
              "record": np.zeros(num_states),
              "counts": np.zeros(num_states), 
              "value_function": np.random.rand(num_states),
              "transition_probabilities": np.ones((num_states, n_actions, num_states)) / num_states,
              "rewards": np.zeros(num_states)}

In [43]:
params["transition_record"]

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [48]:
params["transition_record"][1,2,1]

0.0

In [46]:
params["transition_record"]

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 1., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
k = {"k": 1, "s": 2}

In [21]:
k

{'k': 1, 's': 2}

In [49]:
k = 4 > 3

In [50]:
k

True

In [53]:
np.random.rand(num_states) * 0.1

array([0.08741214, 0.09319601, 0.00236741])