In [1]:
from __future__ import division, print_function
import argparse
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import numpy as np
import os
import random

In [75]:
image = np.random.rand(2,2,3)
num_clusters = 3

In [84]:
image

array([[[0.99265257, 0.87300418, 0.37746384],
        [0.3618112 , 0.13904515, 0.89875278]],

       [[0.09722314, 0.53722427, 0.95119134],
        [0.49212613, 0.92989623, 0.15003278]]])

In [76]:
height = image.shape[0]
width = image.shape[1]
rgb = image.shape[-1]
height

2

In [77]:
centroids = np.zeros((num_clusters, rgb))
centroids

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [91]:
for i in range(num_clusters):
    a = np.random.randint(height)
    b = np.random.randint(width)
    centroids[i] = image[a, b]

centroids_init = centroids

In [94]:
len(centroids_init)

3

In [80]:
a = np.random.randint(height)
b = np.random.randint(width)
a,b

(1, 0)

In [88]:
image

array([[[0.99265257, 0.87300418, 0.37746384],
        [0.3618112 , 0.13904515, 0.89875278]],

       [[0.09722314, 0.53722427, 0.95119134],
        [0.49212613, 0.92989623, 0.15003278]]])

In [90]:
image[0,1]

array([0.3618112 , 0.13904515, 0.89875278])

In [89]:
image[1]

array([[0.09722314, 0.53722427, 0.95119134],
       [0.49212613, 0.92989623, 0.15003278]])

In [97]:
k = 1

In [103]:
if True or True % k == 0:
    print(k)

1


In [110]:
a["k"]=1

TypeError: 'int' object does not support item assignment

In [108]:
k = {}